name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: test
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build version tag Docker image
      run: docker build . --file Dockerfile --tag biletado-assets:v1.0
    - name: Tag Docker image
      run : docker tag biletado-assets:v1.0 ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:v1.0
    - name: Push version tag Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:v1.0
    - name: Build latest tag Docker image
      run: docker build . --file Dockerfile --tag biletado-assets:latest
    - name: Tag latest Docker image
      run : docker tag biletado-assets:latest ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:latest
    - name: Push latest tag Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:latest
