name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build version tag Docker image
      run: docker build . --file Dockerfile --tag biletado-assets:$(date +%s)
    - name: Push version tag Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:$(date +%s)
    - name: Build latest tag Docker image
      run: docker build . --file Dockerfile --tag biletado-assets:latest
    - name: Push latest tag Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/biletado-assets:latest
